version: 2.1

jobs:
  terraform_init:
    docker:
      - image: hashicorp/terraform:light
      - image: amazon/aws-cli
        environment:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

    steps:
      - checkout

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: aws --version

      # Install Terraform
      - run:
          name: Install Terraform
          command: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform

  terraform_plan:
    docker:
      - image: hashicorp/terraform:light
      - image: amazon/aws-cli
        environment:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

    steps:
      - checkout

      # Initialize Terraform
      - run:
          name: Terraform Init
          command: terraform init

      # Generate Terraform plan
      - run:
          name: Terraform Plan
          command: terraform plan

  terraform_apply:
    docker:
      - image: hashicorp/terraform:light
      - image: amazon/aws-cli
        environment:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

    steps:
      - checkout

      # Initialize Terraform
      - run:
          name: Terraform Init
          command: terraform init

      # Apply Terraform changes
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

workflows:
  version: 2
  terraform_flow:
    jobs:
      - terraform_init
      - terraform_plan:
          requires:
            - terraform_init
      - hold:
          type: approval
          requires:
            - terraform_plan
      - terraform_apply:
          requires:
            - hold
