version: 2.1

jobs:
  terraform_init:
    docker:
      - image: hashicorp/terraform:light
      - image: amazon/aws-cli
        environment:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Terraform
          command: terraform --version

      # Initialize AWS CLI
      - run:
          name: Install AWS CLI
          command: aws --version

  terraform_plan:
    docker:
      - image: hashicorp/terraform:light
      - image: amazon/aws-cli
        environment:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Terraform
          command: terraform --version

      # Initialize AWS CLI
      - run:
          name: Install AWS CLI
          command: aws --version

      # Initialize Terraform
      - run:
          name: Terraform Init
          command: terraform init

      # Generate Terraform plan
      - run:
          name: Terraform Plan
          command: terraform plan

  terraform_apply:
    docker:
      - image: hashicorp/terraform:light
      - image: amazon/aws-cli
        environment:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Terraform
          command: terraform --version

      # Initialize AWS CLI
      - run:
          name: Install AWS CLI
          command: aws --version

      # Initialize Terraform
      - run:
          name: Terraform Init
          command: terraform init

      # Apply Terraform changes
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

workflows:
  version: 2
  terraform_flow:
    jobs:
      - terraform_init
      - terraform_plan:
          requires:
            - terraform_init
      - hold:
          type: approval
          requires:
            - terraform_plan
      - terraform_apply:
          requires:
            - hold
